# fatal: [54.145.21.13]: FAILED! => {"changed": false, "failed": true, "msg": "Docker API Error: client and server don't have same version (client : 1.24, server: 1.18)"}

- name: add dockers gpg key
  command: 'apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D'

- name: add dockers repo
  shell: >
    sh -c "echo 'deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -sc) main' | cat > /etc/apt/sources.list.d/docker.list"

- name: Apt-get update
  apt:
    upgrade: yes
    update_cache: yes

- name: install pip and docker
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - python-pip
    - docker-engine

# package needed for ansible's docker module
- name: install docker-py
  pip:
    name: docker-py

- name: create dir for redis data
  file:
    name: /data/redis
    state: directory

- name: data container
  docker:
    name: redis-data
    image: busybox
    state: started
    volumes:
      - /data/redis

- name: redis container
  become: true
  docker:
    name: redis-service
    image: redis
    command: redis-server --appendonly yes
    state: reloaded
    expose: 6379
    ports:
      - 6379:6379
    volumes_from:
      - redis-data
