
- name: install pip
  apt:
    name: python-pip
    state: installed

- name: install docker-py
  pip:
    name: docker-py

- name: rabbitmq container
  become: true
  docker:
    name: rabbitmq-service
    image: rabbitmq
    state: started
    expose: 5672
    ports:
      - 5672:5672
    env:
      RABBITMQ_DEFAULT_PASS: sensu
      RABBITMQ_DEFAULT_USER: sensu
